Proofread of accessibility.md
browserengineering/book pull request #1310
Opened 2024-08-10 02:26 UTC by chrishtr

2024-08-10 02:26 UTC, chrishtr commented on book/accessibility.md
> -*Focus method and events*. Add support for the JavaScript
Duplicate exercise

2024-08-10 02:27 UTC, chrishtr commented on book/accessibility.md
> +14-10 *The `zoom` CSS property*. Add support for the [`zoom`][zoom-property] SSS
Replacement exercise. `zoom` recently acquired a spec (just in 2024!), so it's now appropriate to include.

2024-08-12 17:59 UTC, pavpanchekha requested changes

2024-08-12 17:59 UTC, pavpanchekha commented on book/accessibility.md
> +14-10 *The `zoom` CSS property*. Add support for the [`zoom`][zoom-property] SSS
```suggestion
14-10 *The `zoom` CSS property*. Add support for the [`zoom`][zoom-property] CSS
```

2024-08-12 17:59 UTC, pavpanchekha commented on book/accessibility.md
> +property defined here. This exposes the same functionality as the zoom
What does "defined here" mean here?

2024-08-13 20:28 UTC, pavpanchekha approved these changes

2024-08-13 20:28 UTC, merged