Add zoom
browserengineering/book pull request #792
Opened 2023-04-01 22:28 UTC by chrishtr

2023-04-03 23:14 UTC, pavpanchekha commented
Hi Chris, the `handle_enter` fix is good but the zoom change isn't what I was expecting. I was thinking that we'd have `DocumentLayout` still receive a `zoom` argument to its `layout` method, just like the `frame_width` is, but all other layout objects do not receive it as an argument, and instead compute it like this:

```
class BlockLayout:
    def layout(self):
        self.zoom = self.parent.zoom
```

This means we're computing zoom in basically the same way we compute `width` or `x` or any of the other layout fields, which will make Ch16 more uniform.

2023-04-03 23:15 UTC, pavpanchekha requested changes
For Chapter 16, we want zoom to work like `width` or `x`; see comment on PR.

2023-04-04 00:35 UTC, chrishtr commented
Done, PR updated.

2023-04-04 02:18 UTC, pavpanchekha approved these changes

2023-04-04 02:18 UTC, merged